import * as fs from "node:fs/promises";
import * as path from "node:path";

import { isEnoent } from "@oh-my-pi/pi-utils";

import claudeMainOrchestratorTemplate from "./templates/claude-main-orchestrator.md" with { type: "text" };
import factoryVerifierTemplate from "./templates/factory-verifier.md" with { type: "text" };
import metaPromptTemplate from "./templates/meta-prompt.md" with { type: "text" };
import ompMainOrchestratorTemplate from "./templates/omp-main-orchestrator.md" with { type: "text" };
import stravPaneWorkflowTemplate from "./templates/strav-pane-workflow.md" with { type: "text" };
import verifyOnStopTemplate from "./templates/verify-on-stop.md" with { type: "text" };

interface TemplateFile {
	target: string;
	content: string;
	presets?: readonly FactoryPreset[];
}

export const FACTORY_PRESETS = ["standard", "minimal", "pane-factory", "strav"] as const;

export type FactoryPreset = (typeof FACTORY_PRESETS)[number];

const FACTORY_TEMPLATES: TemplateFile[] = [
	{
		target: ".omp/factory/factory.json",
		content: JSON.stringify(
			{
				template: { name: "software-factory", version: "0.1.0", preset: "__PRESET__" },
				repo: { name: "__REPO_NAME__", kind: "__REPO_KIND__" },
				verifier: {
					enabled: false,
					trigger: "manual",
					agent: "factory-verifier",
					systemPrompt: "../../agents/factory-verifier.md",
					prompt: "prompts/verify-on-stop.md",
					oracle: "scripts/verify.sh",
					maxLoops: 2,
					tools: ["read", "search", "find", "bash"],
				},
				safety: { enabled: true, rulesPath: "safety.rules.json" },
				metaPrompt: { enabled: true, prompt: "prompts/meta-prompt.md" },
				workflow: { enabled: false, default: "piter" },
				memory: { captureCandidates: true, recommendedBackend: "hindsight" },
				paneWorker: {
					enabled: true,
					backend: "cmux",
					orchestratorDefault: "omp",
					workerRuntime: "claude",
					claudeCommand: "claude",
				},
			},
			null,
			2,
		),
	},
	{
		target: ".omp/factory/safety.rules.json",
		content: JSON.stringify(
			{
				version: "0.1.0",
				rules: [
					{
						id: "no-destructive-git",
						description: "Block destructive git operations",
						pattern: "git (push --force|reset --hard|clean -[fd])",
						action: "warn",
					},
					{
						id: "no-rm-rf-root",
						description: "Block recursive root deletion",
						pattern: "rm -rf /",
						action: "block",
					},
				],
			},
			null,
			2,
		),
	},
	{
		target: ".omp/factory/scripts/verify.sh",
		content: `#!/usr/bin/env bash
# Factory verifier oracle — runs build + test + lint.
# Exit 0 = pass, non-zero = fail.
set -euo pipefail
echo "[factory-verifier] Running checks..."
bun run check 2>&1 || { echo "[factory-verifier] FAIL"; exit 1; }
bun run test 2>&1 || { echo "[factory-verifier] FAIL"; exit 1; }
echo "[factory-verifier] PASS"
`,
	},
	{
		target: ".omp/factory/prompts/meta-prompt.md",
		content: metaPromptTemplate,
	},
	{
		target: ".omp/factory/prompts/verify-on-stop.md",
		content: verifyOnStopTemplate,
	},
	{
		target: ".omp/agents/factory-verifier.md",
		content: factoryVerifierTemplate,
	},
	{
		target: ".omp/factory/prompts/claude-main-orchestrator.md",
		content: claudeMainOrchestratorTemplate,
		presets: ["pane-factory", "strav"],
	},
	{
		target: ".omp/factory/prompts/omp-main-orchestrator.md",
		content: ompMainOrchestratorTemplate,
		presets: ["pane-factory", "strav"],
	},
	{
		target: ".omp/factory/workflows/strav-pane-factory.md",
		content: stravPaneWorkflowTemplate,
		presets: ["strav"],
	},
	{
		target: ".omp/factory/model-roles.json",
		content: `${JSON.stringify(
			{
				roles: {
					orchestrator: "current-session",
					worker: "claude-code-pane",
					reviewer: "claude-code-pane",
				},
			},
			null,
			2,
		)}\n`,
		presets: ["strav"],
	},
	{
		target: ".omp/extensions/software-factory/index.ts",
		content: `// Generated by pi-software-factory — runtime safety enforcement and verifier hooks.
// Edit freely; this file is not managed after initial scaffold.
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

export default function softwareFactoryRuntime(pi: ExtensionAPI): void {
	pi.setLabel("Software Factory Runtime");

	// Safety enforcement: block/warn on dangerous tool calls
	pi.on("tool_call", async (event, _ctx) => {
		// Safety rules loaded from .omp/factory/safety.rules.json
		// In future: parse rules and match against event.name / event.params
		void event;
	});

	// Verifier: run after agent completes a turn
	pi.on("agent_end", async (_event, ctx) => {
		const factoryJson = await ctx.sessionManager.getCwd()
			? Bun.file(ctx.sessionManager.getCwd() + "/.omp/factory/factory.json").json().catch(() => null)
			: null;
		if (!factoryJson?.verifier?.enabled) return;
		ctx.ui.notify("Factory verifier would run here (trigger: manual)", "info");
	});
}
`,
	},
	{
		target: ".omp/settings.json",
		content: `${JSON.stringify(
			{
				memory: { backend: "hindsight" },
				extensions: ["./.omp/extensions/software-factory"],
			},
			null,
			2,
		)}\n`,
	},
];

interface ScaffoldOptions {
	cwd: string;
	preset: string;
	enableMemory: boolean;
}

export interface PlannedTemplateFile {
	target: string;
	content: string;
}

export interface ScaffoldResult {
	filesWritten: string[];
	errors: Array<{ target: string; error: string }>;
}

export interface ScaffoldDryRunResult {
	filesToWrite: string[];
	filesSkipped: string[];
	errors: Array<{ target: string; error: string }>;
}

export interface UpgradeDryRunResult {
	create: string[];
	update: string[];
	conflict: Array<{ target: string; error: string }>;
	unchanged: string[];
}

export function getFactoryPresets(): readonly FactoryPreset[] {
	return FACTORY_PRESETS;
}

export function getPlannedFactoryTemplates(options: ScaffoldOptions): PlannedTemplateFile[] {
	const repoName = path.basename(options.cwd);
	return FACTORY_TEMPLATES.filter(
		template => !template.presets || template.presets.includes(options.preset as FactoryPreset),
	).map(template => ({
		target: template.target,
		content: template.content
			.replace("__PRESET__", options.preset)
			.replace("__REPO_NAME__", repoName)
			.replace("__REPO_KIND__", "node"),
	}));
}

async function exists(filePath: string): Promise<boolean> {
	try {
		await fs.access(filePath);
		return true;
	} catch (error) {
		if (isEnoent(error)) return false;
		throw error;
	}
}

async function writeFile(targetPath: string, content: string, overwrite: boolean): Promise<boolean> {
	await fs.mkdir(path.dirname(targetPath), { recursive: true });
	if (!overwrite && (await exists(targetPath))) {
		return false;
	}
	await Bun.write(targetPath, content);
	if (targetPath.endsWith(".sh")) {
		await fs.chmod(targetPath, 0o755);
	}
	return true;
}

export async function scaffoldFactory(options: ScaffoldOptions): Promise<ScaffoldResult> {
	const result: ScaffoldResult = { filesWritten: [], errors: [] };
	for (const template of getPlannedFactoryTemplates(options)) {
		const targetPath = path.join(options.cwd, template.target);
		try {
			if (await writeFile(targetPath, template.content, false)) {
				result.filesWritten.push(template.target);
			}
		} catch (error) {
			result.errors.push({
				target: template.target,
				error: error instanceof Error ? error.message : String(error),
			});
		}
	}
	return result;
}

export async function dryRunScaffoldFactory(options: ScaffoldOptions): Promise<ScaffoldDryRunResult> {
	const result: ScaffoldDryRunResult = { filesToWrite: [], filesSkipped: [], errors: [] };
	for (const template of getPlannedFactoryTemplates(options)) {
		const targetPath = path.join(options.cwd, template.target);
		try {
			if (await exists(targetPath)) {
				result.filesSkipped.push(template.target);
			} else {
				result.filesToWrite.push(template.target);
			}
		} catch (error) {
			result.errors.push({
				target: template.target,
				error: error instanceof Error ? error.message : String(error),
			});
		}
	}
	return result;
}

export async function dryRunUpgradeFactory(options: ScaffoldOptions): Promise<UpgradeDryRunResult> {
	const result: UpgradeDryRunResult = { create: [], update: [], conflict: [], unchanged: [] };
	const templates = getPlannedFactoryTemplates(options).filter(template =>
		template.target.startsWith(".omp/factory/"),
	);
	for (const template of templates) {
		const targetPath = path.join(options.cwd, template.target);
		try {
			if (!(await exists(targetPath))) {
				result.create.push(template.target);
				continue;
			}
			const current = await Bun.file(targetPath).text();
			if (current === template.content) {
				result.unchanged.push(template.target);
			} else {
				result.update.push(template.target);
			}
		} catch (error) {
			result.conflict.push({
				target: template.target,
				error: error instanceof Error ? error.message : String(error),
			});
		}
	}
	return result;
}
