import * as fs from "node:fs/promises";
import * as path from "node:path";

import { isEnoent } from "@oh-my-pi/pi-utils";

/** Embedded template manifest — file content inlined for standalone deployment. */
interface TemplateFile {
	target: string;
	content: string;
}

const FACTORY_TEMPLATES: TemplateFile[] = [
	{
		target: ".omp/factory/factory.json",
		content: JSON.stringify(
			{
				template: { name: "software-factory", version: "0.1.0", preset: "__PRESET__" },
				repo: { name: "__REPO_NAME__", kind: "__REPO_KIND__" },
				verifier: {
					enabled: false,
					trigger: "manual",
					agent: "factory-verifier",
					systemPrompt: "../../agents/factory-verifier.md",
					prompt: "prompts/verify-on-stop.md",
					oracle: "scripts/verify.sh",
					maxLoops: 2,
					tools: ["read", "search", "find", "bash"],
				},
				safety: { enabled: true, rulesPath: "safety.rules.json" },
				metaPrompt: { enabled: true, prompt: "prompts/meta-prompt.md" },
				workflow: { enabled: false, default: "piter" },
				memory: { captureCandidates: true, recommendedBackend: "hindsight" },
			},
			null,
			2,
		),
	},
	{
		target: ".omp/factory/safety.rules.json",
		content: JSON.stringify(
			{
				version: "0.1.0",
				rules: [
					{
						id: "no-destructive-git",
						description: "Block destructive git operations",
						pattern: "git (push --force|reset --hard|clean -[fd])",
						action: "warn",
					},
					{
						id: "no-rm-rf-root",
						description: "Block recursive root deletion",
						pattern: "rm -rf /",
						action: "block",
					},
				],
			},
			null,
			2,
		),
	},
	{
		target: ".omp/factory/scripts/verify.sh",
		content: `#!/usr/bin/env bash
# Factory verifier oracle — runs build + test + lint.
# Exit 0 = pass, non-zero = fail.
set -euo pipefail
echo "[factory-verifier] Running checks..."
bun run check 2>&1 || { echo "[factory-verifier] FAIL"; exit 1; }
bun run test 2>&1 || { echo "[factory-verifier] FAIL"; exit 1; }
echo "[factory-verifier] PASS"
`,
	},
	{
		target: ".omp/factory/prompts/meta-prompt.md",
		content: `# Factory Meta-Prompt

You are operating in a software-factory environment with safety enforcement and a verifier loop.

- Safety rules are enforced before tool execution. Do not attempt to bypass them.
- The verifier may run after your turn to validate your changes.
- Remember important decisions for future sessions.
`,
	},
	{
		target: ".omp/factory/prompts/verify-on-stop.md",
		content: `# Verify on Stop

The agent has completed its turn. Validate the following:

1. All changed files pass type checking (\`bun check\`)
2. All tests pass (\`bun test\`)
3. No linter errors introduced
4. Any new files follow project conventions
`,
	},
	{
		target: ".omp/agents/factory-verifier.md",
		content: `# Factory Verifier

You are a code verifier. Your job is to check that code changes are correct, safe, and follow project conventions.

## Process
1. Read the diff of changed files
2. Run the verify oracle (verify.sh)
3. Report any issues with specific file:line references
4. Suggest fixes for any issues found
`,
	},
	{
		target: ".omp/extensions/software-factory/index.ts",
		content: `// Generated by pi-software-factory — runtime safety enforcement and verifier hooks.
// Edit freely; this file is not managed after initial scaffold.
import type { ExtensionAPI } from "@oh-my-pi/pi-coding-agent";

export default function softwareFactoryRuntime(pi: ExtensionAPI): void {
	pi.setLabel("Software Factory Runtime");

	// Safety enforcement: block/warn on dangerous tool calls
	pi.on("tool_call", async (event, _ctx) => {
		// Safety rules loaded from .omp/factory/safety.rules.json
		// In future: parse rules and match against event.name / event.params
		void event;
	});

	// Verifier: run after agent completes a turn
	pi.on("agent_end", async (_event, ctx) => {
		const factoryJson = await ctx.sessionManager.getCwd()
			? Bun.file(\`\${ctx.sessionManager.getCwd()}/.omp/factory/factory.json\`).json().catch(() => null)
			: null;
		if (!factoryJson?.verifier?.enabled) return;
		ctx.ui.notify("Factory verifier would run here (trigger: manual)", "info");
	});
}
`,
	},
	{
		target: ".omp/settings.json",
		content: JSON.stringify(
			{
				memory: { backend: "hindsight" },
				extensions: ["./.omp/extensions/software-factory"],
			},
			null,
			2,
		),
	},
];

interface ScaffoldOptions {
	cwd: string;
	preset: string;
	enableMemory: boolean;
}

export interface ScaffoldResult {
	filesWritten: string[];
	errors: Array<{ target: string; error: string }>;
}

async function exists(filePath: string): Promise<boolean> {
	try {
		await fs.access(filePath);
		return true;
	} catch (err) {
		if (isEnoent(err)) return false;
		throw err;
	}
}

async function writeFile(targetPath: string, content: string, overwrite: boolean): Promise<void> {
	const dir = path.dirname(targetPath);
	await fs.mkdir(dir, { recursive: true });

	if (!overwrite && (await exists(targetPath))) {
		return; // skip existing files when not overwriting
	}

	await Bun.write(targetPath, content);

	// Make shell scripts executable
	if (targetPath.endsWith(".sh")) {
		await fs.chmod(targetPath, 0o755);
	}
}

export async function scaffoldFactory(options: ScaffoldOptions): Promise<ScaffoldResult> {
	const { cwd, preset } = options;
	const repoName = path.basename(cwd);
	const result: ScaffoldResult = { filesWritten: [], errors: [] };

	for (const template of FACTORY_TEMPLATES) {
		const targetPath = path.join(cwd, template.target);
		try {
			const content = template.content
				.replace("__PRESET__", preset)
				.replace("__REPO_NAME__", repoName)
				.replace("__REPO_KIND__", "node");

			await writeFile(targetPath, content, false);
			result.filesWritten.push(template.target);
		} catch (err) {
			result.errors.push({
				target: template.target,
				error: err instanceof Error ? err.message : String(err),
			});
		}
	}

	return result;
}
